// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDasirrhEmpuEwVJxmLsjWjRvAMY-77mu8',
    appId: '1:556918316594:web:f072258617c1ee709a262b',
    messagingSenderId: '556918316594',
    projectId: 'cloud-77cca',
    authDomain: 'cloud-77cca.firebaseapp.com',
    storageBucket: 'cloud-77cca.appspot.com',
    measurementId: 'G-DEEDHEF20L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7eHmysf1uRdRDBzgiuNLFjqJ-fuofiec',
    appId: '1:556918316594:android:b08877394adaec8f9a262b',
    messagingSenderId: '556918316594',
    projectId: 'cloud-77cca',
    storageBucket: 'cloud-77cca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeenvfz1LG9bp45rr-q6eEK15fSigKA7k',
    appId: '1:556918316594:ios:ac62a728555b57c59a262b',
    messagingSenderId: '556918316594',
    projectId: 'cloud-77cca',
    storageBucket: 'cloud-77cca.appspot.com',
    iosClientId: '556918316594-fqbgtfkjm95v9l9pmoo7bohkrhsi4esr.apps.googleusercontent.com',
    iosBundleId: 'com.example.palliativeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeenvfz1LG9bp45rr-q6eEK15fSigKA7k',
    appId: '1:556918316594:ios:ac62a728555b57c59a262b',
    messagingSenderId: '556918316594',
    projectId: 'cloud-77cca',
    storageBucket: 'cloud-77cca.appspot.com',
    iosClientId: '556918316594-fqbgtfkjm95v9l9pmoo7bohkrhsi4esr.apps.googleusercontent.com',
    iosBundleId: 'com.example.palliativeCare',
  );
}
