// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-D_pFxsxzuCW-ioJvGvGbspqzdbBeFYk',
    appId: '1:222974696650:web:51889fbf4d4f53871b6833',
    messagingSenderId: '222974696650',
    projectId: 'cloud-project-10e23',
    authDomain: 'cloud-project-10e23.firebaseapp.com',
    storageBucket: 'cloud-project-10e23.appspot.com',
    measurementId: 'G-074X48TSKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFlbLNL_am_rwDLhEkN1wY0XImCtwysQI',
    appId: '1:222974696650:android:d8c767f228f52f231b6833',
    messagingSenderId: '222974696650',
    projectId: 'cloud-project-10e23',
    storageBucket: 'cloud-project-10e23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHV04USwn5aC-r0HxEGsKO9vgksvtHVpA',
    appId: '1:222974696650:ios:acb9f7df37e8cd371b6833',
    messagingSenderId: '222974696650',
    projectId: 'cloud-project-10e23',
    storageBucket: 'cloud-project-10e23.appspot.com',
    iosClientId: '222974696650-f79101kso6d9bf15d37grem5fuggoeb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.palliativeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHV04USwn5aC-r0HxEGsKO9vgksvtHVpA',
    appId: '1:222974696650:ios:acb9f7df37e8cd371b6833',
    messagingSenderId: '222974696650',
    projectId: 'cloud-project-10e23',
    storageBucket: 'cloud-project-10e23.appspot.com',
    iosClientId: '222974696650-f79101kso6d9bf15d37grem5fuggoeb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.palliativeCare',
  );
}
